# -*- coding: utf-8 -*-
"""Exploratory Data Analysis of Netflix Titles.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V0dT3f-eiitw49Gjvs8w--HSQSPrVcHY
"""

# ============================================
# NETFLIX DATA ANALYSIS PROJECT
# ============================================

# Import Libraries
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import random

# Set Style
sns.set_style("whitegrid")
plt.rcParams["figure.figsize"] = (10,6)

# --------------------------------------------
# Step 1: Create Synthetic Dataset
# --------------------------------------------

types = ["Movie", "TV Show"]
countries = ["United States", "India", "United Kingdom", "Canada", "France", "Japan"]
ratings = ["TV-MA", "TV-14", "PG-13", "R", "TV-PG"]

data = []

for i in range(1000):
    data.append([
        random.choice(types),
        random.choice(countries),
        random.choice(ratings),
        random.randint(2010, 2023)
    ])

df = pd.DataFrame(data, columns=["type", "country", "rating", "year_added"])

print("Dataset Created Successfully!")
print("Dataset Shape:", df.shape)
print(df.head())

# --------------------------------------------
# 1️⃣ Movies vs TV Shows
# --------------------------------------------

plt.figure()
sns.countplot(data=df, x='type')
plt.title("Distribution of Movies and TV Shows")
plt.xlabel("Content Type")
plt.ylabel("Count")
plt.show()

# --------------------------------------------
# 2️⃣ Top Content Producing Countries
# --------------------------------------------

plt.figure()
df['country'].value_counts().plot(kind='bar')
plt.title("Top Content Producing Countries")
plt.xlabel("Country")
plt.ylabel("Number of Titles")
plt.xticks(rotation=45)
plt.show()

# --------------------------------------------
# 3️⃣ Content Added Over Years
# --------------------------------------------

plt.figure()
df['year_added'].value_counts().sort_index().plot()
plt.title("Content Added Over Years")
plt.xlabel("Year")
plt.ylabel("Number of Titles")
plt.show()

print("\n✅ Analysis Completed Successfully!")